### ISSUE TITLE
Load all  Patreon comments do´s not work anymore

### ISSUE THREAD

**Issue by Peter99ph** [markcnunes/export-patreon-comments#3]
This extension has not been updated for 2 years , it do´s not seem to be working any more.
I have tried 3 different browsers  Brave / Chrome / MS Edge on win 11 it  do´s not work.
Any chance this extension will be updated ?

**Comment by markcnunes** [comment]
@Peter99ph thank you for the comment, I will look into this issue to understand what could be going wrong.

**Comment by markcnunes** [comment]
I haven't been using Patreon anymore so I depend on the feedback to be aware if something isn't working. Patreon changed some of the classes used by the divs that we target for the extension to work. It has been fixed and submitted for Google's review which can take up to 30 days to be approved, hopefully, it won't take this long but I will post here once the new version is available again, @Peter99ph thanks again for the feedback.
